### PR TITLE
Make migrations and seeds optional

### PR DESCRIPTION
**Pull request by rodrigowirth**

### CODE REVIEW

**Comment by pirelenito** [comment]
Hi there! This would a be breaking change, am I right? 

Shouldn't we make it so that it doesn't change the behavior for existing consumers that don't have that flag on their configurations?

**Comment by maxclaus** [comment]
I'm not sure about that. If someone didn't have that configuration before the lib wouldn't even work. So this change won't break any project that was already using it.

**Comment by pirelenito** [comment]
My bad! You are right 👍

**Comment by rodrigowirth** [comment]
You are right @maxcnunes.

**Pull request merged**
